# Generated by Django 4.2 on 2024-10-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_classes_options_alter_lessons_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='lessonName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='science',
            name='scienceName',
            field=models.CharField(max_length=100),
        ),
    ]
