# Generated by Django 4.2 on 2024-10-30 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_lessons_lessonname_alter_science_sciencename'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lessons',
            new_name='LessonsSchool',
        ),
        migrations.RenameModel(
            old_name='Science',
            new_name='SciencesSchool',
        ),
    ]
