# Generated by Django 4.2 on 2024-11-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_rename_lessons_lessonsschool_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonsschool',
            name='pdfFile',
            field=models.FileField(blank=True, null=True, upload_to='pdfFilesSchool'),
        ),
    ]
