# Generated by Django 4.2 on 2024-11-02 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lessonsuni_rename_sciences_sciencesuni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonsuni',
            name='pdfFile',
            field=models.FileField(null=True, upload_to='pdfFilesUniversity'),
        ),
    ]
